# Generated by Django 5.0.4 on 2024-04-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paciente", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consulta",
            name="status",
            field=models.CharField(
                choices=[
                    ("A", "Agendada"),
                    ("F", "Finalizada"),
                    ("C", "Cancelada"),
                    ("I", "Iniciada"),
                ],
                max_length=1,
            ),
        ),
    ]
