# Generated by Django 5.0.4 on 2024-04-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medico", "0002_dadosmedico"),
    ]

    operations = [
        migrations.AddField(
            model_name="dadosmedico",
            name="cim",
            field=models.CharField(default="123", max_length=30),
            preserve_default=False,
        ),
    ]
